require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  NewCops: enable

  Exclude:
    - 'src/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'

RSpec/ContextWording:
  Prefixes:
    - 'and'
    - 'for'
    - 'when'
    - 'with'
    - 'without'

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

RSpec/MultipleMemoizedHelpers:
  Max: 6

Style/AndOr:
  EnforcedStyle: conditionals

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
